import { MOVIE_LIST } from "../utils/movies";

import { useState } from "react";

import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import Alert from "@mui/material/Alert";
import Button from "@mui/material/Button";
import Container from "@mui/material/Container";
import Grid from "@mui/material/Grid";
import TextField from "@mui/material/TextField";
import Typography from "@mui/material/Typography";

import List from "@mui/material/List";
import ListItem from "@mui/material/ListItem";
import ListItemText from "@mui/material/ListItemText";

export default function Home() {
  const [search, setSearch] = useState("");
  const [year, setYear] = useState("");
  const [movies, setMovies] = useState(MOVIE_LIST);

  const handleSubmit = (event) => {
    event.preventDefault();
    console.log(`year: ${year}`);
    console.log(`search: ${search}`);
    filterMovies();
  };

  const filterMovies = () => {
    // Make a copy of the movie list
    let filteredMoviesList = [...MOVIE_LIST];

    // Check if search is empty
    if (search.trim() !== "") {
      // If not empty:
      // loop through movies and check if name includes search
      // Make both lowercase to make it case insensitive
      filteredMoviesList = filteredMoviesList.filter((movieData) => {
        return movieData.name
          .toLowerCase()
          .includes(search.trim().toLowerCase());
      });
    }

    // Check if year is empty
    if (year.trim() !== "") {
      // If not empty:
      // Loop through the movies and check if year is the same
      filteredMoviesList = filteredMoviesList.filter((movieData) => {
        return movieData.year === parseInt(year.trim());
      });
    }

    // Set the movies state to newly filtered list
    setMovies(filteredMoviesList);
  };

  return (
    <div>
      <Head>
        <title>Our Movie App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
      </Head>

      <main>
        <Container>
          <Typography
            variant="h2"
            component="h2"
            style={{ textAlign: "center" }}
          >
            Movies
          </Typography>
          <form style={{ width: "100%" }} onSubmit={handleSubmit}>
            <Grid container spacing={2}>
              <Grid item xs={6}>
                <TextField
                  id="search-field"
                  label="search..."
                  variant="standard"
                  sx={{ width: "100%" }}
                  onChange={(event) => {
                    setSearch(event.target.value);
                  }}
                  value={search}
                />
              </Grid>
              <Grid item xs={4}>
                <TextField
                  id="year-field"
                  label="year"
                  variant="standard"
                  sx={{ width: "100%" }}
                  onChange={(event) => {
                    setYear(event.target.value);
                  }}
                  value={year}
                />
              </Grid>
              <Grid item xs={2}>
                <Button type="submit" variant="contained">
                  Filter
                </Button>
              </Grid>
              <Grid item xs={10}>
                {/* Add the error message here*/}
              </Grid>
            </Grid>
          </form>
          <List sx={{ width: `100%` }}>
            {movies.map((movieData, index) => {
              return (
                <ListItem key={index}>
                  <ListItemText>
                    <Typography variant="p" component="div">
                      {movieData.name} ({movieData.year})
                    </Typography>
                  </ListItemText>
                </ListItem>
              );
            })}
          </List>
        </Container>
      </main>
    </div>
  );
}
