import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

// material ui imports.
import Container from "@mui/material/Container";
import Typography from "@mui/material/Typography";
import Box from "@mui/material/Box";
import Button from "@mui/material/Button";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* 
          The Following line will only install Roboto on this page.
          Later in the course we'll learn about the "document.js"
          page where this will be more appropriate. To have
         */}
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main>
        <Container maxWidth="md">
          <Box sx={{ my: 4 }}>
            <Typography variant="h2" component="h2" color="primary">
              MUI Example
            </Typography>
            <Typography variant="p" component="p" color="secondary">
              You can perhaps see why this is a popular package.
            </Typography>
            <Button variant="contained">Contained</Button>
          </Box>
        </Container>
      </main>
    </div>
  );
}
