import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";

import Container from "@mui/material/Container";
import Box from "@mui/material/Box";
import Button from "@mui/material/Button";
import Grid2 from "@mui/material/Grid2";
import TextField from "@mui/material/TextField";
import List from "@mui/material/List";
import ListItem from "@mui/material/ListItem";
import ListItemText from "@mui/material/ListItemText";
import Typography from "@mui/material/Typography";

import { useState } from "react";

export default function Home() {
  const [todoText, setTodoText] = useState("");
  const [allTodos, setAllTodos] = useState([]);

  const onTodoTextChange = (event) => {
    console.log(event.target.value);
    setTodoText(event.target.value);
  };

  const onTodoClick = () => {
    console.log("clicked");

    let newAllTodos = [...allTodos, todoText];

    setAllTodos(newAllTodos);
    setTodoText("");
  };

  // Condition being used for conditional rendering example
  const shouldShowMessage = true;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
      </Head>
      <div className={`${styles.page}`}>
        <main className={styles.main}>
          <Container>
            <TextField
              id="standard-basic"
              label="New Todo?"
              sx={{ width: "100%", backgroundColor: "white" }}
              variant="filled"
              onChange={onTodoTextChange}
              value={todoText}
            />
            <Button variant="contained" onClick={onTodoClick}>
              Click to Save TODO
            </Button>
            <Grid2 sx={{ backgroundColor: "white" }}>
              The current input text value is: {todoText}
            </Grid2>
            <Grid2>
              <List>
                {allTodos.map((todoItem, index) => {
                  return (
                    <ListItem key={index}>
                      <ListItemText>
                        <Typography variant="p">{todoItem}</Typography>
                      </ListItemText>
                    </ListItem>
                  );
                })}
              </List>
            </Grid2>
            {/** Below is just a hidden message conditional rendering example */}
            {shouldShowMessage ? (
              <p>This is a hidden message</p>
            ) : (
              <p>This is what shows instead of the hidden message</p>
            )}
          </Container>
        </main>
      </div>
    </>
  );
}
