import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import AppBar from "@mui/material/AppBar";
import Box from "@mui/material/Box";
import Button from "@mui/material/Button";

import Container from "@mui/material/Container";

import Toolbar from "@mui/material/Toolbar";
import Typography from "@mui/material/Typography";

import { useState } from "react";

const RANDOM_QUOTE_URL = "https://api.kanye.rest/";

export default function Home() {
  const [quoteData, setQuoteData] = useState({
    quote: "quote here",
    author: "author here",
  });

  const clickHandler = () => {
    // FOR TESTING PURPOSES
    // const newQuoteData = {
    //   quote: "Hi my name is Tom",
    //   author: "Tom Maurer",
    // };
    // setQuoteData(newQuoteData);
    fetch(RANDOM_QUOTE_URL)
      .then((response) => {
        return response.json();
      })
      .then((data) => {
        // Create new quote data object
        const newQuoteData = {
          quote: data.quote,
          author: "Kanye West",
        };
        // Set state for quote data
        setQuoteData(newQuoteData);
      });
  };

  return (
    <div>
      <Head>
        <title>We Love Quotes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
      </Head>
      <AppBar position="relative">
        <Toolbar>
          <Typography variant="h6" color="inherit" noWrap>
            We Love Quotes
          </Typography>
        </Toolbar>
      </AppBar>
      <main>
        <Container maxWidth="sm">
          <Box
            sx={{
              bgcolor: "background.paper",
              pt: 8,
              pb: 6,
            }}
          >
            <Typography
              variant="h5"
              align="center"
              color="text.primary"
              paragraph
            >
              {quoteData.quote}
            </Typography>
            <Typography
              component="h1"
              variant="h4"
              align="center"
              color="text.secondary"
              gutterBottom
            >
              {quoteData.author}
            </Typography>
            <Box display="flex" justifyContent="center">
              <Button variant="contained" onClick={clickHandler}>
                Get New Quote
              </Button>
            </Box>
          </Box>
        </Container>
      </main>
    </div>
  );
}
